root: true

parser: babel-eslint

parserOptions:
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true

plugins:
  - react

env:
  browser: true
  commonjs: true
  es6: true

extends:
  - eslint:recommended
  - plugin:react/recommended

# http://eslint.org/docs/rules/
rules:

  # Possible Errors
  no-template-curly-in-string: 2

  # Best Practices
  accessor-pairs: 2
  array-callback-return: 2
  curly: 2
  default-case: 2
  dot-location: [2, property]
  dot-notation: 2
  eqeqeq: 2
  guard-for-in: 2
  no-alert: 2
  no-caller: 2
  no-div-regex: 2
  no-else-return: 2
  no-empty-function: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implied-eval: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-native-reassign: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-escape: 2
  no-useless-return: 2
  no-void: 2
  no-warning-comments: 1
  no-with: 2
  radix: 2
  yoda: 2

  # Strict Mode
  strict: [2, never]

  # Variables
  no-shadow-restricted-names: 2
  no-undef-init: 2
  no-use-before-define: 2

  # Stylistic Issues
  array-bracket-spacing: 2
  brace-style: [2, 1tbs, allowSingleLine: true]
  camelcase: [2, properties: never]
  comma-spacing: 2
  comma-style: 2
  computed-property-spacing: 2
  eol-last: [2, unix]
  func-style: 2
  indent:
    - 2
    - 4
    - MemberExpression: 1
  jsx-quotes: 2
  key-spacing: 2
  keyword-spacing: 2
  linebreak-style: [2, unix]
  max-depth: 2
  max-len:
    - 2
    - code: 120
      ignoreUrls: true
  max-statements-per-line: [2, max: 2]
  new-cap: 2
  new-parens: 2
  no-lonely-if: 2
  no-multiple-empty-lines: [2, max: 2]
  no-nested-ternary: 2
  no-new-object: 2
  no-spaced-func: 2
  no-trailing-spaces: 2
  no-unneeded-ternary: 2
  no-whitespace-before-property: 2
  object-curly-spacing: 2
  operator-assignment: 2
  operator-linebreak: 2
  padded-blocks: [2, never]
  quotes: [2, single]
  semi: [2, always, omitLastInOneLineBlock: true]
  semi-spacing: 2
  space-before-blocks: 2
  space-before-function-paren: [2, never]
  space-in-parens: 2
  space-unary-ops: 2
  spaced-comment: 2

  # ECMAScript 6
  arrow-spacing: 2
  no-duplicate-imports: [2, includeExports: true]
  no-var: 2
  object-shorthand: [2, methods]
  prefer-arrow-callback: 2
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 2
  template-curly-spacing: 2

  # React - https://github.com/yannickcr/eslint-plugin-react/#list-of-supported-rules
  react/no-children-prop: 2
  react/no-danger: 2
  react/no-deprecated: 2
  react/no-did-mount-set-state: 2
  react/no-did-update-set-state: 2
  react/no-direct-mutation-state: 2
  react/no-find-dom-node: 2
  react/no-is-mounted: 2
  react/no-multi-comp: 2
  react/no-render-return-value: 2
  react/no-string-refs: 2
  react/no-unescaped-entities: 2
  react/no-unknown-property: 2
  react/no-unused-prop-types: 2
  react/prefer-es6-class: 2
  react/prop-types: 2
  react/react-in-jsx-scope: 2
  react/require-default-props: 2
  react/require-render-return: 2
  react/self-closing-comp: 2
  react/style-prop-object: 2

  # JSX - https://github.com/yannickcr/eslint-plugin-react/#jsx-specific-rules
  react/jsx-boolean-value: 2
  react/jsx-closing-bracket-location: [2, after-props]
  react/jsx-curly-spacing: 2
  react/jsx-equals-spacing: 2
  react/jsx-first-prop-new-line: [2, multiline-multiprop]
  react/jsx-handler-names: 2
  react/jsx-indent: [2, 4]
  react/jsx-indent-props: [2, 4]
  react/jsx-key: 2
  react/jsx-no-bind: [2, ignoreRefs: true]
  react/jsx-no-comment-textnodes: 2
  react/jsx-no-duplicate-props: 2
  react/jsx-no-undef: 2
  react/jsx-pascal-case: 2
  react/jsx-space-before-closing: 2
  react/jsx-tag-spacing: 2
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/jsx-wrap-multilines: 2
